"""Seed data extracted from the reviewed launch-window guide.

This is the curated starting garage. It is intentionally faithful to the
cross-referenced sources in the original guide (PC Gamer, Game8, IGN, etc.).
Running ``forza.search`` later layers fresh web findings on top of this.

A note on share codes (carried over from the original guide, and honoured here):
working FH6 tunes live inside the in-game "Find Tuning Setups" marketplace, not
on the open web. Most web-advertised "FH6 codes" are auto-generated, invented, or
recycled FH5 codes that do not transfer. We therefore DO NOT fabricate codes.
Each car carries concrete, reliable tune *specs*; the share-code field stays empty
with an honest status until a verified code is found (the search agent can fill it
from named, reputable tuners and flag it "verify in-game").
"""

META = {
    "game": "Forza Horizon 6",
    "edition_note": "Open-world, Japan map. Released 2026-05-19.",
    "snapshot": "Launch-window meta (curated ~9 days post-launch, late May 2026).",
    "disclaimer": (
        "Launch-window snapshot, not a settled meta. Rankings will shift as players "
        "grind and post tunes. Re-verify high-cost buys against in-game leaderboards "
        "and the Find Tuning Setups marketplace."
    ),
    "pi_bands": "D 100-500 | C 501-600 | B 601-700 | A 701-800 | S1 801-900 | S2 901-998 | R 999/track-only",
    "last_updated": "2026-05-28",
    "data_origin": "Seeded from curated guide; refreshable via free web search.",
}

# Each dict becomes a Car. Keep wording tight — the workbook wraps text.
SEED_CARS = [
    # ===================== ROAD & STREET =====================
    dict(discipline="Road & Street", car_class="R", rank=1, year=2018,
         name="Ferrari FXX-K Evo", pi="R 999", price_cr=4_500_000,
         acquisition="Autoshow (also Welcome Pack)", confidence="Strong",
         strengths="Cleanest R-Class consensus; superb stock speed, handling & braking; only improves tuned.",
         weaknesses="Power can overwhelm you on tight tracks.",
         sources="Game8, IGN, PC Gamer",
         tune_summary="Road/grip baseline. Mech balance ~0.60. Add downforce for touge; brakes + front tyre width before power."),
    dict(discipline="Road & Street", car_class="R", rank=2, year=2023,
         name="Aston Martin Valkyrie", pi="R 999", price_cr=2_750_000,
         acquisition="Autoshow", confidence="Moderate",
         strengths="One of the fastest cars at top speed (default 9.2); handles well tuned.",
         weaknesses="Slow acceleration vs the FXX-K.",
         sources="Game8, IGN",
         tune_summary="Road/grip baseline; longer final drive for straights, shorter for technical circuits."),
    dict(discipline="Road & Street", car_class="R", rank=3, year=2013,
         name="McLaren P1", pi="R 999", price_cr=1_550_000,
         acquisition="Autoshow", confidence="Moderate",
         strengths="Lightning top speed for road/street.",
         weaknesses="Comparatively slow acceleration; weaker on very twisty courses.",
         sources="Game8",
         tune_summary="Road/grip baseline; favour speed-zone gearing on open layouts."),

    dict(discipline="Road & Street", car_class="S2", rank=1, year=2021,
         name="Mercedes-AMG One", pi="S2 ~950", price_cr=None,
         acquisition="Autoshow", confidence="Moderate",
         strengths="Perfect 10 acceleration; active aero dominant on technical high-speed circuits. Meta S2 road pick.",
         weaknesses="Pricey; rewards smooth inputs.",
         sources="Game8, multiple tier lists",
         tune_summary="Road/grip baseline; mech balance 0.60; lean on aero in fast corners."),
    dict(discipline="Road & Street", car_class="S2", rank=2, year=2025,
         name="GR GT Prototype (Toyota)", pi="S2", price_cr=250_000,
         acquisition="Autoshow (listed under 'GR')", confidence="Strong",
         strengths="PC Gamer's single favourite; cover car. Slicks + widened track = exceptionally planted. Standout value.",
         weaknesses="None notable for the price.",
         sources="PC Gamer",
         tune_summary="Road/grip baseline; already planted — minimal alignment tweaks needed."),
    dict(discipline="Road & Street", car_class="S2", rank=3, year=2020,
         name="Koenigsegg Jesko", pi="S2", price_cr=None,
         acquisition="Autoshow", confidence="Moderate",
         strengths="Leads S2 in raw top speed; best for long straights / speed zones.",
         weaknesses="Needs careful tuning to corner.",
         sources="Game8",
         tune_summary="Top-speed gearing (long final drive); soften to settle the rear on corner entry."),

    dict(discipline="Road & Street", car_class="S1", rank=1, year=2024,
         name="Nissan GT-R NISMO", pi="S1", price_cr=270_000,
         acquisition="Autoshow / Touge & Street Rivals milestones", confidence="Strong",
         strengths="Go-to S1. AWD traction, ~600 hp, quick off the line; ideal for bend-heavy tracks. Base game, no DLC.",
         weaknesses="Heavier than RWD rivals.",
         sources="Game8, multiple",
         tune_summary="Road/grip baseline; AWD diff ~70% rear; mech balance 0.60."),
    dict(discipline="Road & Street", car_class="S1", rank=2, year=2023,
         name="Porsche 911 GT3 RS", pi="S1", price_cr=260_000,
         acquisition="Autoshow", confidence="Strong",
         strengths="Quintessential street racer; slicks + wider base = perfect for tight tracks.",
         weaknesses="Not the highest top speed.",
         sources="Game8, PC Gamer",
         tune_summary="Road/grip baseline; shorter final drive for technical city/mountain routes."),
    dict(discipline="Road & Street", car_class="S1", rank=3, year=2023,
         name="Porsche 911 Turbo S", pi="S1", price_cr=275_000,
         acquisition="Autoshow", confidence="Moderate",
         strengths="10 launch stat, strong acceleration; accessible and very tunable.",
         weaknesses="Understeers if front tyres left stock.",
         sources="Game8",
         tune_summary="Road/grip baseline; widen front tyres + brakes before power."),

    dict(discipline="Road & Street", car_class="A", rank=1, year=2020,
         name="Toyota GR Supra", pi="A", price_cr=None,
         acquisition="Autoshow", confidence="Moderate",
         strengths="Cleanest modern-JDM A pick; most flexible platform (road/drift/CC). Well-tuned it punches into S1.",
         weaknesses="Needs tuning to shine.",
         sources="Game8, PC Gamer",
         tune_summary="Road/grip baseline; the workhorse — tune to the event."),
    dict(discipline="Road & Street", car_class="A", rank=2, year=2020,
         name="BMW M2 Competition Coupe", pi="A", price_cr=None,
         acquisition="Autoshow", confidence="Moderate",
         strengths="Traditional A option with better speed/handling balance.",
         weaknesses="Less adaptable than the Supra.",
         sources="Game8",
         tune_summary="Road/grip baseline; balanced springs, slight forward brake bias."),

    dict(discipline="Road & Street", car_class="B", rank=1, year=2021,
         name="Volkswagen Golf R", pi="B", price_cr=None,
         acquisition="Autoshow", confidence="Tentative",
         strengths="Cited as strongest AWD all-rounder for B-Class road.",
         weaknesses="Early / single-weighted claim — verify.",
         sources="Single source",
         tune_summary="Road/grip baseline; AWD diff bias rear; keep it under the 700 PI ceiling."),
    dict(discipline="Road & Street", car_class="B", rank=2, year=1969,
         name="Toyota 2000GT", pi="B", price_cr=None,
         acquisition="Barn Find (must be located)", confidence="Tentative",
         strengths="Standout B-Class pick.",
         weaknesses="Barn Find — not buyable until found.",
         sources="Single source",
         tune_summary="Road/grip baseline; classic chassis — modest power, lean on handling."),

    # ===================== DRAG & TOP SPEED =====================
    dict(discipline="Drag & Top Speed", car_class="S2", rank=1, year=2012,
         name="Nissan GT-R Black Edition (R35) 'Forza Edition'", pi="S2 ~850", price_cr=None,
         acquisition="Wheelspins / Auction House only (not Autoshow)", confidence="Strong",
         strengths="Consensus fastest drag car. Pre-tuned AWD, drag tyres + chute, 10/10/10 speed/accel/launch, ~6s quarter mile.",
         weaknesses="Near-uncontrollable in corners — straight-line only. Forza Edition, can't be bought outright.",
         sources="Skycoach, community consensus",
         tune_summary="Drag tune (comes pre-tuned). Top gear long; tune 1st gear iteratively on the strip."),
    dict(discipline="Drag & Top Speed", car_class="S2", rank=2, year=2020,
         name="Koenigsegg Jesko", pi="S2", price_cr=None,
         acquisition="Autoshow", confidence="Moderate",
         strengths="Top-speed king for speed-trap / half-mile pulls.",
         weaknesses="Not as quick off the line as the AWD GT-R FE.",
         sources="Community",
         tune_summary="Top-speed build: longest viable final drive; minimal downforce."),
    dict(discipline="Drag & Top Speed", car_class="S2", rank=3, year=None,
         name="Hennessey Venom F5", pi="S2", price_cr=None,
         acquisition="Autoshow", confidence="Moderate",
         strengths="Raw-power top-speed pick (community clocked 315+ mph).",
         weaknesses="Less forgiving than the GT-R FE.",
         sources="Community",
         tune_summary="Top-speed gearing; controllable wheelspin off the line."),
    dict(discipline="Drag & Top Speed", car_class="B", rank=4, year=1994,
         name="Mazda MX-5 Miata 'Forza Edition'", pi="S2 ~850", price_cr=475_000,
         acquisition="Autoshow / Auction House", confidence="Moderate",
         strengths="Best accessible drag pick; lightweight AWD. Get accel + launch to 10 via tune.",
         weaknesses="Disagreement vs GT-R FE on outright pace.",
         sources="GAMES.gg",
         tune_summary="Drag tyres; hard-launch diff with controllable wheelspin; long top gear."),
    dict(discipline="Drag & Top Speed", car_class="A", rank=5, year=1998,
         name="Toyota Supra RZ", pi="A", price_cr=None,
         acquisition="Autoshow", confidence="Moderate",
         strengths="Cheapest credible drag starter.",
         weaknesses="Needs upgrades to compete up-class.",
         sources="Community",
         tune_summary="Drag tune; prioritise launch + 1st-gear tuning on the strip."),

    # ===================== DRIFT =====================
    dict(discipline="Drift", car_class="S1", rank=1, year=2020,
         name="Formula Drift #151 Toyota GR Supra", pi="S1", price_cr=185_000,
         acquisition="Autoshow", confidence="Strong",
         strengths="Glides and smokes even stock; FD cars outperform any B-class drift build.",
         weaknesses="Pricier than entry drifters.",
         sources="Game8, Switchblade",
         tune_summary="Drift tune: front tyre near-max PSI, rear low; max front camber, rear ~0, front toe-out; locked accel diff; forward brake bias."),
    dict(discipline="Drift", car_class="S2", rank=2, year=None,
         name="Lotus Evija 'Forza Edition'", pi="S2", price_cr=None,
         acquisition="Wheelspin-exclusive", confidence="Moderate",
         strengths="S2 drift specialist — electric instant torque.",
         weaknesses="Wheelspin-only; twitchier than ICE drifters.",
         sources="Switchblade",
         tune_summary="Drift tune; manage instant torque with rear PSI + brake bias."),
    dict(discipline="Drift", car_class="S1", rank=3, year=None,
         name="Formula Drift #64 Nissan Z", pi="S1", price_cr=None,
         acquisition="Autoshow", confidence="Moderate",
         strengths="Scores high, holds angle, less twitchy than electric drift cars — good for beginners.",
         weaknesses="Edged out by the #151 Supra at the top.",
         sources="Switchblade",
         tune_summary="Drift tune; slightly softer than the #151 for forgiveness."),
    dict(discipline="Drift", car_class="A", rank=4, year=2002,
         name="Nissan Silvia Spec-R", pi="A", price_cr=44_000,
         acquisition="Autoshow", confidence="Strong",
         strengths="Unassuming but swings around corners; strong engine + wide drift tyres; clears most challenges.",
         weaknesses="Outscored by Formula Drift cars in open zones.",
         sources="Game8",
         tune_summary="Drift tune; wide rear drift tyres; stiff rear springs; rear toe-out."),
    dict(discipline="Drift", car_class="A", rank=5, year=2022,
         name="Mazda MX-5 Miata RF", pi="A", price_cr=29_000,
         acquisition="Autoshow", confidence="Strong",
         strengths="RWD, well-balanced; loves to go sideways and chains drifts without spinning. Any MX-5 works.",
         weaknesses="Low power ceiling.",
         sources="Game8",
         tune_summary="Drift tune; forgiving balance — great learner drifter."),
    dict(discipline="Drift", car_class="B", rank=6, year=None,
         name="Toyota AE86 Sprinter Trueno 'Forza Edition'", pi="B", price_cr=None,
         acquisition="Autoshow", confidence="Moderate",
         strengths="The 'correct' car for Mt. Haruna touge by physics (~980 kg, high-revving).",
         weaknesses="Low power — keep power secondary.",
         sources="PC Gamer",
         tune_summary="Stiff rear springs, rear toe-out, 1.5-way or open LSD; keep power secondary to balance."),

    # ===================== DIRT & RALLY =====================
    dict(discipline="Dirt & Rally", car_class="A", rank=1, year=2022,
         name="Subaru BRZ 'Forza Edition'", pi="A", price_cr=None,
         acquisition="Aftermarket spot at Sotoyama Ski Resort (not Autoshow)", confidence="Strong",
         strengths="Perfect 10 off-road rating; a beast in both dirt and cross-country when tuned.",
         weaknesses="Must be located at the Aftermarket spot.",
         sources="Game8",
         tune_summary="Rally tune: 22-27 PSI, soft springs near minimum, ride height 5-7in off bump stops, center diff 60-70% rear."),
    dict(discipline="Dirt & Rally", car_class="A", rank=2, year=2001,
         name="Ford #4 Focus RS (rally)", pi="A", price_cr=415_000,
         acquisition="Autoshow", confidence="Moderate",
         strengths="PC Gamer default: scrappy, high speed + accel + off-road handling.",
         weaknesses="Costlier than B-class value picks.",
         sources="PC Gamer",
         tune_summary="Rally tune; soft, high ride height; shorter gearing."),
    dict(discipline="Dirt & Rally", car_class="B", rank=3, year=2004,
         name="Subaru Impreza WRX STI", pi="B", price_cr=30_000,
         acquisition="Autoshow", confidence="Strong",
         strengths="Iconic, dirt-cheap; good general stat spread with headroom before hitting A-rank.",
         weaknesses="Needs a rally conversion for higher classes.",
         sources="Game8",
         tune_summary="Rally tune; AWD; build up to the B ceiling, then bump to A when ready."),
    dict(discipline="Dirt & Rally", car_class="B", rank=4, year=2004,
         name="Mitsubishi Lancer Evolution VIII MR", pi="B", price_cr=30_000,
         acquisition="Autoshow (Welcome Pack version pre-tuned to A)", confidence="Strong",
         strengths="Near-identical to the Impreza, slightly higher stats across the board.",
         weaknesses="Same conversion needs up-class.",
         sources="Game8",
         tune_summary="Rally tune; Welcome Pack copy arrives pre-tuned to A-rank."),

    # ===================== CROSS-COUNTRY =====================
    dict(discipline="Cross-Country", car_class="S1", rank=1, year=None,
         name="Dodge Viper 'Forza Edition' / GTS ACR FE", pi="S1+", price_cr=None,
         acquisition="Premium edition / VIP only", confidence="Strong",
         strengths="Best S1+ cross-country: incredibly fast and lightweight, nothing comparable right now.",
         weaknesses="Premium/VIP locked. Free alternative: Subaru BRZ FE.",
         sources="Game8",
         tune_summary="Cross-country tune: suspension for stability + durability; soft, raised ride height."),
    dict(discipline="Cross-Country", car_class="A", rank=2, year=None,
         name="Mercedes-Benz X-Class", pi="A", price_cr=None,
         acquisition="Autoshow", confidence="Moderate",
         strengths="Best A-Class CC pick; consistent across all CC track types.",
         weaknesses="Not the fastest outright.",
         sources="Game8",
         tune_summary="Cross-country tune; prioritise stability and suspension travel."),
    dict(discipline="Cross-Country", car_class="B", rank=3, year=None,
         name="Ford F-450 (Super Duty)", pi="D-B", price_cr=None,
         acquisition="Autoshow", confidence="Strong",
         strengths="Best choice for any race in D-B; consistent across all cross-country tracks.",
         weaknesses="Heavy; not for higher classes.",
         sources="Game8",
         tune_summary="Cross-country tune; soft long-travel suspension; durability first."),
    dict(discipline="Cross-Country", car_class="A", rank=4, year=2023,
         name="Ford F-150 Raptor R", pi="A", price_cr=110_000,
         acquisition="Autoshow", confidence="Moderate",
         strengths="Huge power and great for ramming.",
         weaknesses="Ugly handling on paper — tune handling first, then top speed.",
         sources="Game8",
         tune_summary="Cross-country tune; fix handling/stability before chasing top speed."),
    dict(discipline="Cross-Country", car_class="A", rank=5, year=2025,
         name="Toyota Land Cruiser", pi="A", price_cr=70_000,
         acquisition="Autoshow", confidence="Moderate",
         strengths="Reliable all-terrain.",
         weaknesses="Needs accel + braking tuned for bendy tracks.",
         sources="Game8",
         tune_summary="Cross-country tune; raise accel + braking for technical CC layouts."),
]

# Honest default for every seed car: no fabricated codes.
DEFAULT_CODE_STATUS = "No verified public code — build in-game via Find Tuning Setups (see Tuning sheet)"

# --- Tuning baselines (per discipline) --------------------------------------
TUNE_BASELINES = [
    dict(setting="Tire pressure",
         road="Slicks 30-33 PSI; street/rally 26-28",
         rally="22-27 PSI",
         drift="Front near max, rear low (rear spins easier)",
         drag="Drag tyres, low for launch"),
    dict(setting="Springs / ARBs",
         road="Stiffer, balanced", rally="Soft, near minimum",
         drift="Stiff rear", drag="-"),
    dict(setting="Ride height",
         road="Low", rally="Higher (5-7 in, off bump stops)",
         drift="Low", drag="Low"),
    dict(setting="Alignment",
         road="-1.5 to -2.5 deg front camber, slight front toe-out",
         rally="Softer",
         drift="Max front camber, rear ~0, toe-out front",
         drag="Minimal"),
    dict(setting="Differential",
         road="~65% accel / 15% decel RWD; AWD ~70% rear",
         rally="Drop ~10% vs race; center 60-70% rear",
         drift="Locked on accel (drift diff)",
         drag="Tuned for hard launch w/ controllable wheelspin"),
    dict(setting="Brake balance",
         road="Slight forward", rally="-",
         drift="Forward (brake mid-drift w/o snapping)", drag="-"),
    dict(setting="Gearing",
         road="Shorter final drive (mountain/city); longer (straights)",
         rally="Shorter", drift="Tune last on a straight",
         drag="Top gear long; 1st iteratively on the strip"),
]

MECH_BALANCE = (
    "New FH6 stat — a live front-vs-rear grip readout. Target 0.55-0.65 "
    "(sweet spot 0.60 for road racing). Adjust primarily with anti-roll bars. "
    "Rule: soften the end with the problem; don't stiffen the strong end."
)

TUNE_ORDER = ("Tires -> Springs -> Ride Height -> Alignment -> ARBs -> "
              "Damping -> Brakes -> Differential -> Aero -> Gearing")

UNIVERSAL_TIPS = [
    "Install adjustable 'Race' parts (Race Suspension/Diff, tunable gearbox) first or sliders stay locked.",
    "Change ONE setting at a time and test on the same stretch of road (the golden rule).",
    "Upgrade brakes + front tyre width BEFORE adding power — they move the needle more than in past Forzas.",
    "Tyre-pressure changes are subtle but cumulative; a 3 PSI shift transforms behaviour.",
    "Sliding in corners? Drop rear pressure 1-2 PSI before touching suspension.",
    "Japan's map is vertical — corner-exit cars beat raw-horsepower cars on the touge.",
    "FH6 rebalanced classes: old Forza tunes can't be imported — build from scratch.",
]

HOW_TO_GET_CODES = [
    "Real, current codes live in-game, and update as the meta shifts:",
    "1. Own the car -> Cars tab -> Upgrades & Tuning.",
    "2. Find Tuning Setups -> Search (Backspace on PC).",
    "3. Filter by event type (drag/drift/rally/road) and sort by most downloaded / highest rated.",
    "4. Download, test on a fixed stretch, keep if it suits the event.",
    "Web-advertised 'FH6 codes' are largely auto-generated, invented, or recycled FH5 codes that don't transfer.",
]

# --- Sources ----------------------------------------------------------------
SOURCES_TRUSTED = [
    "PC Gamer (Rory Norris, 30+ hrs hands-on)",
    "Game8 (per-class + off-road/CC guides)",
    "grindout (cites Game8 + IGN consensus)",
    "IGN", "fh6guide", "fandomwire",
    "gamingpromax (Mechanical Balance)",
    "forza.guide", "GAMES.gg", "skycoach",
    "Dexerto wiki", "Switchblade (drift)", "forzatune.com",
]

SOURCES_CAUTION = ["ggwtb", "fh6hub", "xmodhub", "narcosis", "armadaboost"]

CONFIDENCE_KEY = {
    "Strong": "Multiple independent reputable sources agree.",
    "Moderate": "Appears across guides but with disagreement or single-source weighting.",
    "Tentative": "Early / contested; verify in-game before committing credits.",
}
