"""Seed data for the FH6 tier list.

Curated from the original launch-window guide (PC Gamer, Game8, IGN, Dexerto,
gamingpromax, Switchblade, etc.) and expanded with a fresh web research pass to
fill every class (D -> R) across every discipline.

Confidence is graded honestly. Many FH6 outlets do NOT publish exact per-car PI
numbers yet (the game is new), so the tier list shows each class's PI BAND — that
is the real "number value" tied to the tier, and is the build target you tune to.

On tune codes: verbatim FH6 share codes are not reliably published on the open web
(most web "codes" are auto-generated, invented, or recycled FH5 codes that don't
transfer; real codes live in-game and in maintained tuner spreadsheets/Discords).
We do NOT fabricate codes. Each car's tune cell points to where a REAL code lives,
marked with * (see the * legend on the Tuning sheet), and the --refresh agent will
fold in literal codes if/when reputable ones get posted.
"""

META = {
    "game": "Forza Horizon 6",
    "edition_note": "Open-world, Japan map. Released 2026-05-19.",
    "snapshot": "Launch-window meta, curated + web-refreshed (late May 2026).",
    "disclaimer": (
        "Launch-window snapshot, not a settled meta. Rankings will shift as players "
        "grind and post tunes. Exact per-car PI is rarely published yet, so the PI "
        "column shows each class's band (your build target). Re-verify high-cost buys "
        "in-game."
    ),
    "pi_bands": "D 100-500 | C 501-600 | B 601-700 | A 701-800 | S1 801-900 | S2 901-998 | R 999/track-only",
    "last_updated": "2026-05-28",
}

# Per-discipline pointer to where REAL tune codes live (marked * in the workbook).
CODE_SOURCES = {
    "Road & Street": "In-game Find Tuning Setups: search car, filter Road, sort top-rated *",
    "Drag & Top Speed": "In-game Find Tuning Setups: filter Drag, sort top-rated; also YouTube drag-tune videos *",
    "Drift": "JSR Chronic FH6 tune sheet (Forza Forums) + in-game Drift filter, sort top-rated *",
    "Dirt & Rally": "In-game Find Tuning Setups: filter Dirt/Rally, sort top-rated *",
    "Cross-Country": "In-game Find Tuning Setups: filter Cross-Country, sort top-rated *",
}

# Real share codes captured from the Dexerto FH6 tuning-codes page.
# 9-digit codes shown as three groups. Marked * (community-sourced; verify in-game).
# Add more as you screenshot the rest of the Dexerto / community lists.
TUNE_CODES = [
    dict(car="1962 Peel P50", pi="D 100", code="531 816 165",
         best_for="Speed on straights", source="Dexerto"),
    dict(car="2007 Alfa Romeo 8C Competizione", pi="A 635", code="759 705 340",
         best_for="Drifting", source="Dexerto"),
    dict(car="2017 Ferrari J50", pi="S1 772", code="145 195 403",
         best_for="Speed", source="Dexerto"),
]

# The * legend, shown on the Tuning sheet and Overview.
CODE_LEGEND = (
    "* = community-sourced pointer, NOT a verified code. Verbatim FH6 share codes "
    "aren't reliably published online yet — most web 'codes' are auto-generated, "
    "invented, or recycled FH5 codes that don't transfer. Open the in-game Find "
    "Tuning Setups marketplace (or the linked tuner sheet), download a top-rated tune, "
    "and confirm it on a fixed stretch of road before trusting it."
)

DEFAULT_CODE_STATUS = CODE_LEGEND

# Each dict becomes a Car. rank = best-in-block (1 = top pick for that discipline+class).
SEED_CARS = [
    # ============================ ROAD & STREET ============================
    dict(discipline="Road & Street", car_class="D", rank=1, year=1965,
         name="Toyota Sports 800", price_cr=None, acquisition="Autoshow (cheap)",
         confidence="Moderate",
         strengths="~580 kg; sharpest handling on tight, technical D-class tracks.",
         weaknesses="Very low power; struggles on long straights.",
         sources="gamingpromax"),
    dict(discipline="Road & Street", car_class="C", rank=1, year=1961,
         name="Jaguar E-Type S1", price_cr=None, acquisition="Autoshow",
         confidence="Tentative",
         strengths="Cited as best C-class all-rounder; strong balance.",
         weaknesses="Needs tuning to reach the class ceiling.",
         sources="Game8"),
    dict(discipline="Road & Street", car_class="B", rank=1, year=2009,
         name="Audi RS 6", price_cr=None, acquisition="Autoshow",
         confidence="Moderate",
         strengths="Strong speed + handling; traditional B option.",
         weaknesses="Heavy vs hot-hatch rivals.",
         sources="Game8"),
    dict(discipline="Road & Street", car_class="B", rank=2, year=2021,
         name="Volkswagen Golf R", price_cr=None, acquisition="Autoshow",
         confidence="Tentative",
         strengths="Strong AWD all-rounder for B-Class road.",
         weaknesses="Early / single-weighted claim — verify.",
         sources="Single source"),
    dict(discipline="Road & Street", car_class="B", rank=3, year=1969,
         name="Toyota 2000GT", price_cr=None, acquisition="Barn Find (must be located)",
         confidence="Tentative",
         strengths="Standout classic B-Class pick.",
         weaknesses="Barn Find — not buyable until found.",
         sources="Single source"),
    dict(discipline="Road & Street", car_class="A", rank=1, year=2020,
         name="Toyota GR Supra", price_cr=None, acquisition="Autoshow",
         confidence="Strong",
         strengths="Most adaptable A platform (road/drift/CC); well-tuned it punches into S1.",
         weaknesses="Jack-of-all-trades; not class-leading raw pace.",
         sources="Game8, PC Gamer"),
    dict(discipline="Road & Street", car_class="A", rank=2, year=2020,
         name="BMW M2 Competition Coupe", price_cr=None, acquisition="Autoshow",
         confidence="Moderate",
         strengths="Traditional A option with strong speed/handling balance.",
         weaknesses="Less adaptable than the Supra.",
         sources="Game8"),
    dict(discipline="Road & Street", car_class="A", rank=3, year=1993,
         name="Jaguar XJ220", price_cr=None, acquisition="Autoshow / Auction House",
         confidence="Moderate",
         strengths="Excellent for fast, open road events.",
         weaknesses="Less agile in tight corners.",
         sources="gamingpromax"),
    dict(discipline="Road & Street", car_class="S1", rank=1, year=2024,
         name="Nissan GT-R NISMO", price_cr=270_000,
         acquisition="Autoshow / Touge & Street Rivals milestones", confidence="Strong",
         strengths="Go-to S1: AWD traction, ~600 hp, quick off the line; bend-heavy tracks. Base game.",
         weaknesses="Heavy; AWD understeer if mistuned.",
         sources="Game8, Dexerto"),
    dict(discipline="Road & Street", car_class="S1", rank=2, year=2023,
         name="Porsche 911 GT3 RS", price_cr=260_000, acquisition="Autoshow",
         confidence="Strong",
         strengths="Quintessential street racer; slicks + wide base = perfect for tight tracks.",
         weaknesses="Not the highest top speed.",
         sources="Game8, PC Gamer"),
    dict(discipline="Road & Street", car_class="S1", rank=3, year=2023,
         name="Porsche 911 Turbo S", price_cr=275_000, acquisition="Autoshow",
         confidence="Moderate",
         strengths="10 launch stat; near-perfect top speed/handling/braking; very tunable.",
         weaknesses="Tricky at the limit until tuned.",
         sources="gamingpromax"),
    dict(discipline="Road & Street", car_class="S2", rank=1, year=2021,
         name="Mercedes-AMG One", price_cr=2_700_000,
         acquisition="Autoshow (also Wheelspin / loyalty)", confidence="Strong",
         strengths="Perfect 10 acceleration; active aero dominant on technical high-speed circuits. Meta S2 road pick.",
         weaknesses="Very expensive; demanding on bumpy streets.",
         sources="Game8, Dexerto"),
    dict(discipline="Road & Street", car_class="S2", rank=2, year=2025,
         name="GR GT Prototype (Toyota)", price_cr=250_000,
         acquisition="Autoshow (listed under 'GR')", confidence="Strong",
         strengths="PC Gamer's favourite; cover car. Slicks + widened track = exceptionally planted. Standout value.",
         weaknesses="None notable for the price.",
         sources="PC Gamer"),
    dict(discipline="Road & Street", car_class="S2", rank=3, year=2020,
         name="Koenigsegg Jesko", price_cr=None, acquisition="Autoshow",
         confidence="Moderate",
         strengths="Leads S2 in raw top speed; best for long straights / speed zones.",
         weaknesses="Needs careful tuning to corner.",
         sources="Game8"),
    dict(discipline="Road & Street", car_class="R", rank=1, year=2018,
         name="Ferrari FXX-K Evo", price_cr=4_500_000,
         acquisition="Autoshow (also Welcome Pack)", confidence="Strong",
         strengths="Cleanest R consensus; superb stock speed, handling & braking; only improves tuned.",
         weaknesses="Power can overwhelm on tight tracks; track-focused.",
         sources="Game8, Dexerto, gamingpromax"),
    dict(discipline="Road & Street", car_class="R", rank=2, year=2023,
         name="Aston Martin Valkyrie", price_cr=2_750_000, acquisition="Autoshow",
         confidence="Moderate",
         strengths="One of the fastest cars at top speed (default 9.2); handles well tuned.",
         weaknesses="Slow acceleration vs the FXX-K.",
         sources="Game8"),
    dict(discipline="Road & Street", car_class="R", rank=3, year=2013,
         name="McLaren P1", price_cr=1_550_000, acquisition="Autoshow",
         confidence="Moderate",
         strengths="Lightning top speed for road/street.",
         weaknesses="Slow acceleration; weaker on very twisty courses.",
         sources="Game8"),

    # ============================ DRAG & TOP SPEED ============================
    dict(discipline="Drag & Top Speed", car_class="D", rank=1, year=1991,
         name="Honda Beat", price_cr=15_000, acquisition="Autoshow",
         confidence="Tentative",
         strengths="Cheap, light D-class drag entry.",
         weaknesses="Tiny power; bottom of the ladder.",
         sources="Game8"),
    dict(discipline="Drag & Top Speed", car_class="B", rank=1, year=1998,
         name="Toyota Supra RZ", price_cr=90_000, acquisition="Autoshow",
         confidence="Moderate",
         strengths="Best budget build; tunes up to challenge hypercars.",
         weaknesses="Needs heavy AWD/power swap to compete up-class.",
         sources="gamingpromax"),
    dict(discipline="Drag & Top Speed", car_class="S1", rank=1, year=2012,
         name="Nissan GT-R Black Edition (R35)", price_cr=80_000, acquisition="Autoshow",
         confidence="Moderate",
         strengths="Cheap AWD launch base for drag builds.",
         weaknesses="Stock top end limited.",
         sources="Game8"),
    dict(discipline="Drag & Top Speed", car_class="S2", rank=1, year=2012,
         name="Nissan GT-R Black Edition (R35) 'Forza Edition'", price_cr=None,
         acquisition="Wheelspins / Auction House only", confidence="Strong",
         strengths="Consensus best all-round drag: factory chute, AWD, ~3,000 hp, consistent ~6s quarter mile.",
         weaknesses="RNG to obtain; near-uncontrollable in corners (straight-line only).",
         sources="Game8, gamingpromax, community"),
    dict(discipline="Drag & Top Speed", car_class="S2", rank=2, year=1994,
         name="Mazda MX-5 Miata 'Forza Edition'", price_cr=500_000,
         acquisition="Aftermarket spot (Festival KM Drag Meet) / Auction House",
         confidence="Strong",
         strengths="Best out-of-box drag car; AWD + stock drag tyres, insane launch.",
         weaknesses="Falls off on very long top-speed strips.",
         sources="Game8"),
    dict(discipline="Drag & Top Speed", car_class="S2", rank=3, year=2021,
         name="Hennessey Venom F5", price_cr=None, acquisition="Autoshow / Auction House",
         confidence="Moderate",
         strengths="Raw top-speed king (community clocked ~315+ mph).",
         weaknesses="Traction-limited launch; poor for short drags.",
         sources="Dexerto, community"),
    dict(discipline="Drag & Top Speed", car_class="R", rank=1, year=2019,
         name="Toyota Tacoma TRD Pro 'Forza Edition'", price_cr=None,
         acquisition="Wheelspin / FE reward", confidence="Moderate",
         strengths="AWD monster launch, dialled for drag out of the box.",
         weaknesses="Poor top-end speed.",
         sources="Game8"),

    # ============================ DRIFT ============================
    dict(discipline="Drift", car_class="D", rank=1, year=None,
         name="Toyota Sprinter Trueno GT Apex (AE86)", price_cr=None,
         acquisition="Autoshow (cheap)", confidence="Strong",
         strengths="~980 kg + high-rev 4A-GE rotates faster than anything in D; holds angle on min throttle.",
         weaknesses="Tiny power ceiling; outclassed once tuned past D.",
         sources="Switchblade"),
    dict(discipline="Drift", car_class="C", rank=1, year=2022,
         name="Mazda MX-5 Miata RF", price_cr=29_000, acquisition="Autoshow",
         confidence="Strong",
         strengths="Friendliest learner; chains drifts without spinning on drift tyres. Any MX-5 works.",
         weaknesses="Low stock power; wants forced induction.",
         sources="PC Gamer"),
    dict(discipline="Drift", car_class="C", rank=2, year=None,
         name="Nissan Silvia (S13)", price_cr=None, acquisition="Autoshow (early career)",
         confidence="Moderate",
         strengths="Forgiving, cheap to upgrade, available early.",
         weaknesses="Needs power tuning to shine.",
         sources="Switchblade"),
    dict(discipline="Drift", car_class="B", rank=1, year=1994,
         name="Nissan Silvia K's (S14)", price_cr=None, acquisition="Autoshow",
         confidence="Strong",
         strengths="Most balanced Silvia; SR20DET predictable, clean linked angle, no snap oversteer.",
         weaknesses="Mid power until built (~400-450 hp target).",
         sources="Switchblade"),
    dict(discipline="Drift", car_class="B", rank=2, year=None,
         name="Toyota JZX100 Chaser", price_cr=None, acquisition="Autoshow",
         confidence="Moderate",
         strengths="1JZ-GTE, long wheelbase great for long passes / Tokyo expressways.",
         weaknesses="Heavy; less agile in tight switchbacks.",
         sources="Switchblade"),
    dict(discipline="Drift", car_class="B", rank=3, year=None,
         name="Toyota AE86 Sprinter Trueno 'Forza Edition'", price_cr=None,
         acquisition="Wheelspin / FE reward", confidence="Moderate",
         strengths="Adds power without changing the chassis balance; the 'correct' touge car (Mt. Haruna).",
         weaknesses="FE acquisition only.",
         sources="Switchblade, PC Gamer"),
    dict(discipline="Drift", car_class="A", rank=1, year=2002,
         name="Nissan Silvia Spec-R (S15)", price_cr=44_000, acquisition="Autoshow",
         confidence="Strong",
         strengths="Community 'king of sliding'; technical precision, wide drift tyres, clears most challenges.",
         weaknesses="Outscored by Formula Drift cars in open zones.",
         sources="Game8, PC Gamer"),
    dict(discipline="Drift", car_class="A", rank=2, year=None,
         name="Ford Mustang Dark Horse", price_cr=None, acquisition="Autoshow",
         confidence="Moderate",
         strengths="Best muscle drift: power, aggressive rotation, wide lines.",
         weaknesses="Hard to keep straight; heavy.",
         sources="PC Gamer"),
    dict(discipline="Drift", car_class="S1", rank=1, year=2020,
         name="Formula Drift #151 Toyota GR Supra", price_cr=185_000, acquisition="Autoshow",
         confidence="Strong",
         strengths="Safest overall pick; glides and smokes even stock, checks every box.",
         weaknesses="Premium FD purchase.",
         sources="Game8, Switchblade"),
    dict(discipline="Drift", car_class="S1", rank=2, year=None,
         name="Formula Drift #64 Forsberg Nissan Z", price_cr=None, acquisition="Autoshow",
         confidence="Strong",
         strengths="Best for most players: easy to buy/tune, 3-stars most drift zones, less twitchy.",
         weaknesses="Spec FD car, less customizable.",
         sources="Game8"),
    dict(discipline="Drift", car_class="S1", rank=3, year=None,
         name="Formula Drift #99 Mazda RX-8", price_cr=None, acquisition="Autoshow",
         confidence="Moderate",
         strengths="Rotary drifts very controllable, easy to handle.",
         weaknesses="Rotary fuel/heat quirks.",
         sources="Game8"),
    dict(discipline="Drift", car_class="S2", rank=1, year=None,
         name="Lotus Evija 'Forza Edition'", price_cr=None, acquisition="Wheelspin-exclusive",
         confidence="Moderate",
         strengths="S2 drift specialist — electric instant torque.",
         weaknesses="Wheelspin-only; twitchier than ICE drifters.",
         sources="Switchblade"),

    # ============================ DIRT & RALLY ============================
    dict(discipline="Dirt & Rally", car_class="D", rank=1, year=1970,
         name="GMC Jimmy", price_cr=60_000, acquisition="Prologue starter / Autoshow",
         confidence="Strong",
         strengths="Built for rough routes, 9.3 off-road rating; free early.",
         weaknesses="Slow on clean road.",
         sources="gamingpromax"),
    dict(discipline="Dirt & Rally", car_class="C", rank=1, year=None,
         name="Toyota Celica GT-Four ST205", price_cr=None,
         acquisition="Prologue starter / Autoshow", confidence="Strong",
         strengths="AWD traction, mixed-surface flexibility, best top speed of the starters.",
         weaknesses="Not a pure dirt specialist.",
         sources="gamingpromax"),
    dict(discipline="Dirt & Rally", car_class="B", rank=1, year=2004,
         name="Subaru Impreza WRX STI", price_cr=30_000, acquisition="Autoshow",
         confidence="Strong",
         strengths="Iconic, dirt-cheap; great general spread with headroom before hitting A-rank.",
         weaknesses="Stock power modest; needs conversion up-class.",
         sources="PC Gamer, Game8"),
    dict(discipline="Dirt & Rally", car_class="B", rank=2, year=2004,
         name="Mitsubishi Lancer Evolution VIII MR", price_cr=30_000,
         acquisition="Autoshow (Welcome Pack version pre-tuned to A)", confidence="Strong",
         strengths="Reliable AWD out of the box; hard to beat on dirt/rally.",
         weaknesses="Heavier than tuned rivals.",
         sources="gamingpromax"),
    dict(discipline="Dirt & Rally", car_class="B", rank=3, year=None,
         name="Ford RS200 Evolution", price_cr=None, acquisition="Autoshow / Auction House",
         confidence="Moderate",
         strengths="Short wheelbase, light, huge corner manoeuvrability; proven dirt weapon.",
         weaknesses="Twitchy at high speed.",
         sources="PC Gamer"),
    dict(discipline="Dirt & Rally", car_class="A", rank=1, year=2022,
         name="Subaru BRZ 'Forza Edition'", price_cr=None,
         acquisition="Aftermarket spot at Sotoyama Ski Resort", confidence="Strong",
         strengths="Perfect 10 off-road rating; a beast in both dirt and cross-country tuned.",
         weaknesses="Must be located at the Aftermarket spot.",
         sources="Game8"),
    dict(discipline="Dirt & Rally", car_class="A", rank=2, year=None,
         name="Mitsubishi Lancer Evolution VI", price_cr=None, acquisition="Autoshow",
         confidence="Strong",
         strengths="AWD + turbo + balanced chassis; fast and stable on loose dirt.",
         weaknesses="Needs a rally conversion to fully optimize.",
         sources="gamingpromax"),
    dict(discipline="Dirt & Rally", car_class="A", rank=3, year=2001,
         name="Ford #4 Focus RS (rally)", price_cr=415_000, acquisition="Autoshow",
         confidence="Moderate",
         strengths="Scrappy: high speed + accel + off-road handling.",
         weaknesses="Costlier than B-class value picks.",
         sources="PC Gamer"),
    dict(discipline="Dirt & Rally", car_class="S1", rank=1, year=None,
         name="Audi Sport Quattro S1", price_cr=None, acquisition="Autoshow",
         confidence="Moderate",
         strengths="Go-to traditional rally car; iconic AWD turbo.",
         weaknesses="Older chassis vs converted exotics.",
         sources="Game8"),
    dict(discipline="Dirt & Rally", car_class="S1", rank=2, year=None,
         name="Lotus Exige WTAC (rally conversion)", price_cr=None,
         acquisition="Autoshow / Aftermarket", confidence="Moderate",
         strengths="Once rally-converted, one of the best dirt-race cars overall.",
         weaknesses="Requires a full rally conversion.",
         sources="Game8"),
    dict(discipline="Dirt & Rally", car_class="S2", rank=1, year=None,
         name="Porsche 917 'Forza Edition' (rally conversion)", price_cr=None,
         acquisition="FE / Wheelspin", confidence="Tentative",
         strengths="Top-tier converted rally option at high PI.",
         weaknesses="FE-only; needs full conversion.",
         sources="Game8"),

    # ============================ CROSS-COUNTRY ============================
    dict(discipline="Cross-Country", car_class="D", rank=1, year=None,
         name="Ford F-450 (Super Duty)", price_cr=None, acquisition="Autoshow",
         confidence="Strong",
         strengths="Best D-class CC pick; consistent across every cross-country track.",
         weaknesses="Bulky; slow on tarmac.",
         sources="Game8"),
    dict(discipline="Cross-Country", car_class="C", rank=1, year=None,
         name="Ford F-450 (Super Duty)", price_cr=None, acquisition="Autoshow",
         confidence="Strong",
         strengths="Carries straight into C: durable, consistent on all CC track types.",
         weaknesses="Bulky; slow on tarmac.",
         sources="Game8"),
    dict(discipline="Cross-Country", car_class="B", rank=1, year=None,
         name="Ford F-450 (Super Duty)", price_cr=None, acquisition="Autoshow",
         confidence="Strong",
         strengths="Game8's best pick across all of D-B; consistent every tier.",
         weaknesses="Bulky; slow on tarmac; not for higher classes.",
         sources="Game8"),
    dict(discipline="Cross-Country", car_class="A", rank=1, year=None,
         name="Mercedes-Benz X-Class", price_cr=None, acquisition="Autoshow",
         confidence="Strong",
         strengths="Best A-class CC pick; consistent on all cross-country race types.",
         weaknesses="Not the fastest outright.",
         sources="Game8"),
    dict(discipline="Cross-Country", car_class="A", rank=2, year=2023,
         name="Ford F-150 Raptor R", price_cr=110_000, acquisition="Autoshow",
         confidence="Moderate",
         strengths="Huge power and great for ramming.",
         weaknesses="Ugly handling on paper — tune handling first, then top speed.",
         sources="Game8"),
    dict(discipline="Cross-Country", car_class="A", rank=3, year=2025,
         name="Toyota Land Cruiser", price_cr=70_000, acquisition="Autoshow",
         confidence="Moderate",
         strengths="Reliable all-terrain.",
         weaknesses="Needs accel + braking tuned for bendy tracks.",
         sources="Game8"),
    dict(discipline="Cross-Country", car_class="S1", rank=1, year=None,
         name="Dodge Viper 'Forza Edition' / GTS ACR FE", price_cr=None,
         acquisition="Premium edition / VIP only", confidence="Strong",
         strengths="Best S1+ CC: incredibly fast and lightweight, nothing comparable for speed.",
         weaknesses="Paywalled (VIP/Premium). Free alternative: Subaru BRZ FE.",
         sources="Game8"),
    dict(discipline="Cross-Country", car_class="S1", rank=2, year=2022,
         name="Subaru BRZ 'Forza Edition'", price_cr=None,
         acquisition="Aftermarket spot at Sotoyama Ski Resort", confidence="Strong",
         strengths="Best FREE S1+ pick; excellent control on loose surfaces, handles CC well.",
         weaknesses="RWD-biased vs trucks on the roughest terrain.",
         sources="Game8"),
    dict(discipline="Cross-Country", car_class="S2", rank=1, year=None,
         name="Ford Bronco R", price_cr=None, acquisition="Autoshow",
         confidence="Moderate",
         strengths="Factory off-road tyres, perfect 10 off-road rating; excels at huge drops (~6,500 lb durability).",
         weaknesses="Heavy, ~325 hp, low handling rating (~4).",
         sources="PC Gamer"),
]

# --- Tuning baselines (per discipline) --------------------------------------
TUNE_BASELINES = [
    dict(setting="Tire pressure",
         road="Slicks 30-33 PSI; street/rally 26-28",
         rally="22-27 PSI",
         drift="Front near max, rear low (rear spins easier)",
         drag="Drag tyres, low for launch"),
    dict(setting="Springs / ARBs",
         road="Stiffer, balanced", rally="Soft, near minimum",
         drift="Stiff rear", drag="-"),
    dict(setting="Ride height",
         road="Low", rally="Higher (5-7 in, off bump stops)",
         drift="Low", drag="Low"),
    dict(setting="Alignment",
         road="-1.5 to -2.5 deg front camber, slight front toe-out",
         rally="Softer",
         drift="Max front camber, rear ~0, toe-out front",
         drag="Minimal"),
    dict(setting="Differential",
         road="~65% accel / 15% decel RWD; AWD ~70% rear",
         rally="Drop ~10% vs race; center 60-70% rear",
         drift="Locked on accel (drift diff)",
         drag="Tuned for hard launch w/ controllable wheelspin"),
    dict(setting="Brake balance",
         road="Slight forward", rally="-",
         drift="Forward (brake mid-drift w/o snapping)", drag="-"),
    dict(setting="Gearing",
         road="Shorter final drive (mountain/city); longer (straights)",
         rally="Shorter", drift="Tune last on a straight",
         drag="Top gear long; 1st iteratively on the strip"),
]

MECH_BALANCE = (
    "New FH6 stat — a live front-vs-rear grip readout. Target 0.55-0.65 "
    "(sweet spot 0.60 for road racing). Adjust primarily with anti-roll bars. "
    "Rule: soften the end with the problem; don't stiffen the strong end."
)

TUNE_ORDER = ("Tires -> Springs -> Ride Height -> Alignment -> ARBs -> "
              "Damping -> Brakes -> Differential -> Aero -> Gearing")

UNIVERSAL_TIPS = [
    "Install adjustable 'Race' parts (Race Suspension/Diff, tunable gearbox) first or sliders stay locked.",
    "Change ONE setting at a time and test on the same stretch of road (the golden rule).",
    "Upgrade brakes + front tyre width BEFORE adding power — they move the needle more than in past Forzas.",
    "Tyre-pressure changes are subtle but cumulative; a 3 PSI shift transforms behaviour.",
    "Sliding in corners? Drop rear pressure 1-2 PSI before touching suspension.",
    "Japan's map is vertical — corner-exit cars beat raw-horsepower cars on the touge.",
    "FH6 rebalanced classes: old Forza tunes can't be imported — build from scratch.",
]

HOW_TO_GET_CODES = [
    "Real, current codes live in-game and update as the meta shifts:",
    "1. Own the car -> Cars tab -> Upgrades & Tuning.",
    "2. Find Tuning Setups -> Search (Backspace on PC).",
    "3. Filter by event type (drag/drift/rally/road) and sort by most downloaded / highest rated.",
    "4. Download, test on a fixed stretch, keep if it suits the event.",
]

# Named places where real codes are published. Open these on your phone/PC and
# copy the code into the in-game Find Tuning Setups search box.
CODE_LINKS = [
    ("Dexerto — Best tuning codes (Peel P50, BMW M3 & more)",
     "https://www.dexerto.com/wikis/forza-horizon-6/best-tuning-codes-forza-horizon-6/"),
    ("Dexerto — Garage share codes",
     "https://www.dexerto.com/wikis/forza-horizon-6/garage-share-codes/"),
    ("ForzaFire — browse all FH6 tunes by car/class/event",
     "https://www.forzafire.com/builds"),
    ("JSR Chronic FH6 Tunes — spreadsheet + Discord (Forza Forums)",
     "https://forums.forza.net/t/jsr-chronic-fh6-tunes-spreadsheet-share-codes-discord/826030"),
    ("r/ForzaHorizon — community posts new tunes after each weekly playlist reset",
     "https://www.reddit.com/r/ForzaHorizon/"),
]

# --- Sources ----------------------------------------------------------------
SOURCES_TRUSTED = [
    "PC Gamer (Rory Norris, 30+ hrs hands-on)",
    "Game8 (per-class + per-discipline guides)",
    "Dexerto wiki (per-class tier lists)",
    "grindout (cites Game8 + IGN consensus)",
    "gamingpromax (per-class + Mechanical Balance)",
    "Switchblade (drift)",
    "IGN", "fh6guide", "fandomwire", "forza.guide", "GAMES.gg",
    "skycoach", "forzatune.com",
    "JSR Chronic tune sheet (Forza Forums)",
]

SOURCES_CAUTION = ["ggwtb", "fh6hub", "xmodhub", "narcosis", "armadaboost", "gamerstation (calculator output)"]

CONFIDENCE_KEY = {
    "Strong": "Multiple independent reputable sources agree.",
    "Moderate": "Appears across guides but with disagreement or single-source weighting.",
    "Tentative": "Early / contested / snippet-only; verify in-game before committing credits.",
}
